services:
  - type: web
    name: ara-pink-api
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    plan: free 
